language: python
python:
  - "3.6"      # current default Python on Travis CI
  - "3.7"
  - "3.8"
install:
  - pip install -r requirements.txt
  - pip install flake8

script:
  # Check code style
  - flake8 . --show-source
  # Run tests
  - python -m unittest discover .